//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTagPocket.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTagPocket.Resources.ResourceApp", typeof(ResourceApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string AppHelp {
            get {
                return ResourceManager.GetString("AppHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error in the application.
        /// </summary>
        public static string FatalErrorUnexpected {
            get {
                return ResourceManager.GetString("FatalErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during application initialization.
        /// </summary>
        public static string InitAppFatalError {
            get {
                return ResourceManager.GetString("InitAppFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string ProcessIdle {
            get {
                return ResourceManager.GetString("ProcessIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string ProcessPaused {
            get {
                return ResourceManager.GetString("ProcessPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string ProcessRunning {
            get {
                return ResourceManager.GetString("ProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basic theme for MyTagPocket..
        /// </summary>
        public static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It serves as an example of the Theme definition in the application. Changes in this file do not affect the application itself..
        /// </summary>
        public static string ThemeDescriptionExample {
            get {
                return ResourceManager.GetString("ThemeDescriptionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Database.
        /// </summary>
        public static string UpgradeDatabaseLabel {
            get {
                return ResourceManager.GetString("UpgradeDatabaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating.
        /// </summary>
        public static string UpgradeInfoFinishError {
            get {
                return ResourceManager.GetString("UpgradeInfoFinishError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update completed successfully.
        /// </summary>
        public static string UpgradeInfoFinishSucces {
            get {
                return ResourceManager.GetString("UpgradeInfoFinishSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update not started.
        /// </summary>
        public static string UpgradeInfoNotStarted {
            get {
                return ResourceManager.GetString("UpgradeInfoNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update started.
        /// </summary>
        public static string UpgradeInfoStarted {
            get {
                return ResourceManager.GetString("UpgradeInfoStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with error.
        /// </summary>
        public static string UpgradeStatusEndError {
            get {
                return ResourceManager.GetString("UpgradeStatusEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed.
        /// </summary>
        public static string UpgradeStatusEndSucces {
            get {
                return ResourceManager.GetString("UpgradeStatusEndSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string UpgradeStatusNotStart {
            get {
                return ResourceManager.GetString("UpgradeStatusNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string UpgradeStatusProgress {
            get {
                return ResourceManager.GetString("UpgradeStatusProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string UpgradeStatusStop {
            get {
                return ResourceManager.GetString("UpgradeStatusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating basic user content structures..
        /// </summary>
        public static string UpgradeStorageContentsDescriptionLabel {
            get {
                return ResourceManager.GetString("UpgradeStorageContentsDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage contents.
        /// </summary>
        public static string UpgradeStorageContentsLabel {
            get {
                return ResourceManager.GetString("UpgradeStorageContentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Storage.
        /// </summary>
        public static string UpgradeStorageLabel {
            get {
                return ResourceManager.GetString("UpgradeStorageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating application settings and their configuration parts..
        /// </summary>
        public static string UpgradeStorageSettingsDescriptionLabel {
            get {
                return ResourceManager.GetString("UpgradeStorageSettingsDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete update settings.
        /// </summary>
        public static string UpgradeStorageSettingsError {
            get {
                return ResourceManager.GetString("UpgradeStorageSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage settings is last version.
        /// </summary>
        public static string UpgradeStorageSettingsIsActual {
            get {
                return ResourceManager.GetString("UpgradeStorageSettingsIsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage settings.
        /// </summary>
        public static string UpgradeStorageSettingsLabel {
            get {
                return ResourceManager.GetString("UpgradeStorageSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update setup completed successfully.
        /// </summary>
        public static string UpgradeStorageSettingSucces {
            get {
                return ResourceManager.GetString("UpgradeStorageSettingSucces", resourceCulture);
            }
        }
    }
}
